# Changes here will be overwritten by Copier
_commit: 0.1.0
_src_path: https://github.com/Ingenjorsarbete-For-Klimatet/ifk-python-template.git
author: Mladen Gibanica
email: 11275336+mgcth@users.noreply.github.com
module_name: lantmateriet
package_name: geometry
project_description: Parse data from Lantmäteriet.
project_name: ifk-lantmateriet
